print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
a1 = name1.lower()
a2 = name2.lower()
t1 = a1.count('t')
r1 = a1.count('r')
u1 = a1.count('u')
e1 = a1.count('e')
t2 = a2.count('t')
r2 = a2.count('r')
u2 = a2.count('u')
e2 = a2.count('e')
l1 = a1.count('l')
o1 = a1.count('o')
v1 = a1.count('v')
ee1 = a1.count('e')
l2 = a2.count('l')
o2 = a2.count('o')
v2 = a2.count('v')
ee2 = a2.count('e')
add1 = (t1 + r1 + u1 + e1) + (t2 + r2 + u2 + e2)
add2 = (l1 + o1 + v1 + ee1) + (l2 + o2 + v2 + ee2)
num_str = str(add1) + str(add2)
num = int(num_str)
if (num < 10) or (num > 90):
  print(f"Your score is {num}, you go together like coke and mentos.")
elif (num <= 50) and (num >= 40):
  print(f"Your score is {num}, you are alright together.")
else :
  print(f"Your score is {num}.")

