adjective_1 = input("Type an adjective: ")
adjective_2 = input("Type another adjective: ")
type_of_bird = input("Enter a type of bird: ")
room =  input("Enter a room in the house: ")
past_tense_verb = input("Enter a verb (in past tense): ")
verb = input("Enter a verb: ")
relative_name = input("Enter a name: ")
noun = input("Enter a noun: ")
liquid_type = input("Input a type of liquid: ")
verb_ing = input("Enter a verb ending in -ing: ")
body_part = input("Input a body part (plural): ")
plural_noun = input("Input a plural noun: ")
ing_verb = input("Type another verb ending in -ing: ")
noun_2 = input("Type another noun: ")

print("It was a " + adjective_1 + ", cold November day. I woke up to the " + adjective_2 + " smell of " + type_of_bird)
print("roasting in the " + room + " downstairs. I " + past_tense_verb + " down the stairs to see if I could help " + verb)
print('the dinner. My Mom said, "See if ' + relative_name + ' needs a fresh ' + noun +'." So I carried a tray of glasses full of ')
print(liquid_type + " into the " + verb_ing + " room. When I got there, I couldn't believe my " + body_part + "! There were ")
print(plural_noun + " " + ing_verb + " on the " + noun_2 + "!")
